### ISSUE TITLE
Hardcoded file paths

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#1]
There are a few instances of file paths hardcoded into the scripts, making it impossible to run on different compute:

- bin/combine_hyb_merge: `use lib '/homes/tollervey/lib';`
- bin/remove_duplicate_hybrids_hOH5.pl: `use lib '/homes/gkudla/bin';`
- bin/bowtie2: `LC_ALL=C singularity run /datastore/library/software/biocontainers/containers/bowtie2/2.3.4.3/bowtie2%3A2.3.4.3--py37he860b03_1 bowtie2 "$@"`
- bin/hyb2.yml: `prefix: /datastore/homes3/ljianyo/miniconda3/envs/hyb2`

For the Perl scripts, any scripts used in these locations should be added to this repo and referenced in `bin`. The call to Singularity should reference the remote BioContainers repository instead. For the Conda .yml file, the 'prefix' line should be removed

**Comment by Jylau14** [comment]
Changed to " use lib '~/hyb2/bin' ; "

I will remove bowtie2 and install it on conda instead(?)

Removed hyb2.yml prefix.

**Comment by mwhamgenomics** [comment]
The pipeline might not necessarily be installed at ~/hyb2 - to make this portable, I'd use [FindBin](https://perldoc.perl.org/FindBin) instead:

```perl
use FindBin;
use lib "$FindBin::Bin";
use Hybrid_long_2;
```
