### ISSUE TITLE
Command line help message

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#3]
It's common for command line tools to have a help message showing what arguments the executable takes, e.g. by running with no arguments or running with `--help` or `-h`. At the moment there's no option for this - if I run `bin/hyb2` with no options, the executable hangs indefinitely. It would be nice to have a default help message that shows if:

- no arguments are specified
- incorrect arguments are specified
- some kind of `--help` option is used - although I'm not sure if Bash `getopts` can do this

**Comment by Jylau14** [comment]
Now echos "No options selected" and exits when no arguments are specified to prevent it from hanging indefinitely.
