### ISSUE TITLE
Missing dependency: unafold/hybrid-min

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#4]
The pipeline uses [hybrid-min](http://www.unafold.org/Dinamelt/unafold-man-pages/hybrid-min.php) and optionally hybrid-min-ss, but there's no mention of it in the setup steps. Installation/compiling of Unafold should be added as a setup step before running this pipeline.

I should also raise a concern that Unafold seems to be [very difficult to acquire](http://www.unafold.org/forum/viewtopic.php?t=17). Luckily my system already had it installed, but for the benefit of other users who don't have it, I'd recommend considering alternative, more freely available software for this step if possible.

**Comment by Jylau14** [comment]
For now, uploaded UNAfold scripts.
