### ISSUE TITLE
Missing dependency: make_hyb_db

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#5]
This pipeline runs the command `make_hyb_db`, which appears to come from [here](https://github.com/gkudla/hyb/tree/master/bin)? This in turn relies on ncbi-blast and makeblastdb. Ncbi-blast should be added to the setup steps, and the part that calls it should be added to this pipeline.

**Comment by Jylau14** [comment]
Uploaded faToTwoBit and will install others on conda.

**Comment by mwhamgenomics** [comment]
make_hyb_db appears to be missing again, so should be added back in
