### ISSUE TITLE
Gzipped input

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#6]
It's common for fastqs to be compressed into fastq.gz files, but currently `bin/hyb2` [only checks for *.fasta and *.fastq, and bowtie never runs if the input is *.fastq.gz](https://github.com/Jylau14/hyb2/blob/dcf769c0843040e43befe674572b87c12b53a92d/bin/hyb2#L73-L100). When I try running with a fastq.gz, I get:

```
$ PATH=$PATH:path/to/hyb2/bin hyb2 -i hyb2_prepared_inputs/NR2_collapsed.fastq.gz -1 ../NORAD_and_18S.fasta -o test_run -a ZIKV-PE243-2015_virusRNA -b NR003286.4_RNA18SN5_rRNA -x 7501 -y 501 -l 500
Processing SAM file...
_hybrids_ua.bit_1.fasta: No such file or directory
Error! Aborting! Check input arguments.
```

I also get some funny side-effects, where a bunch of empty files get created in my working directory:
- `-d`
- _hybrids_ua.bit_1.fasta-_hybrids_ua.bit_2.fasta.dG
- _mtophits.blast
- _singleE.blast_stats.txt
- _hybrids.fasta
- _hybrids_ua.bit_1.fasta-_hybrids_ua.bit_2.fasta.run
- _mtophits.ref
- _TEMP_FILE1_TXT
- _hybrids.hyb
- _hybrids_ua.hyb
- _singleE.blast
- test_run.ZIKV-PE243-2015_virusRNA.entire.txt 

Most of them have no prefix, and one is named `-d`, presumably because `$OUT` never gets set.

An acceptable fix for now would be:
- check the name of the input file
- if it ends in '.gz', exit and give an error message saying that only uncompressed input is allowed

Longer term, a better fix would be to make sure all the steps work with gzipped input (most bioinformatics tools like bowtie should be okay anyway)

**Comment by Jylau14** [comment]
Now allow .gz extension.
