### ISSUE TITLE
Missing dependency: singularity

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#7]
The `bin/bowtie2` script runs bowtie in singularity, which might not be installed in other systems, and bowtie2 2.3.4.3 is available on Conda anyway. The `singularity run` command should be replaced with a simple call to `bowtie2`, and `bowtie2=2.3.4.3` should be added to bin/hyb2.yml.

**Comment by Jylau14** [comment]
Thank you. I will look at these issues and try to fix them.

**Comment by mwhamgenomics** [comment]
No problem! From looking at the script again, it refers to locations in the filesystem that don't exist on my system, so it seems to be tailored to a specific system.

It also just runs `bowtie2 $@` in the end, so I think this script can be removed. This will make the bowtie2_fast*2sam scripts run bowtie2 directly

**Comment by Jylau14** [comment]
Yes, I had a look at the file and deleted it.
Thank you!
