### ISSUE TITLE
Missing dependency: hybrid_stats

### ISSUE THREAD

**Issue by mwhamgenomics** [Jylau14/hyb2#8]
The script `sam2hyb` calls the script 'hybrid_stats', which doesn't exist here. There is a hybrid_stats_2, but there's also a script [here](https://github.com/gkudla/hyb/blob/master/bin/hybrid_stats). We should review which one to use and either:

- change the `hybrid_stats` call in sam2hyb to `hybrid_stats_2`
- add hybrid_stats in this repo; remove hybrid_stats_2

**Comment by Jylau14** [comment]
Uploaded hybrid_stats_2.
